---
root: true

extends:
  - airbnb-base
  - plugin:import/typescript
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended

settings:
  import/resolver: typescript


rules:
  semi: off
  semi-style: [error, first]
  max-len: [warn, 100]
  max-params: [error, 3]
  no-param-reassign: off
  class-methods-use-this: off
  consistent-return: off
  no-restricted-syntax: off
  no-shadow: off
  no-console: [warn, { allow: [debug, error] }]

  import/extensions: [error, never]
  import/prefer-default-export: off

  '@typescript-eslint/semi': [error, never]
  '@typescript-eslint/no-unused-vars': ["error", { "argsIgnorePattern": "^_" }]

ignorePatterns:
  - dist
  - .parcel-cache
  - node_modules
