root: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:import/typescript
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict

settings:
  import/resolver: typescript

parserOptions:
  project: tsconfig.json

rules:
  semi-style: [error, first]
  no-param-reassign: off
  class-methods-use-this: off
  consistent-return: off
  no-console: [warn, { allow: [debug, error] }]

  import/extensions: [error, never]
  import/prefer-default-export: off

  '@typescript-eslint/semi': [error, never]
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/no-unused-vars': ["error", { "argsIgnorePattern": "^_" }]
  '@typescript-eslint/unbound-method': ["error", { "ignoreStatic": true }]

overrides:
  - files: '*.spec.ts'
    rules:
      prefer-arrow-callback: off
      func-names: off
      no-restricted-globals: off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-non-null-assertion': off

ignorePatterns:
  - dist
  - .parcel-cache
  - node_modules
  - '*.js'
