root: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:import/typescript
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict

settings:
  import/resolver: typescript

parserOptions:
  project: tsconfig.json

rules:
  semi-style: [error, first]
  no-param-reassign: off
  class-methods-use-this: off
  consistent-return: off
  no-console: [warn, { allow: [debug, error] }]

  import/extensions: [error, never]
  import/prefer-default-export: off

  '@typescript-eslint/semi': [error, never]
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/no-unused-vars': ["error", { "argsIgnorePattern": "^_" }]

ignorePatterns:
  - dist
  - .parcel-cache
  - node_modules
